
kind: Deployment
apiVersion: api/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    web: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector: 
    matchLabels:
      web: frontend
      tier: web
      project: expense
  template:
    metadata:
      name: frontend
      labels:
        web: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: anjaneyareddym/frontend:v2   
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec: 
  type: LoadBalancer
  selector:
      web: frontend
      tier: web
      project: expense
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port           


      


