apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: app
    project: expense
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      name: backend
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: anjaneyareddym/backend:v2 
        envFrom:
        - configMapRef:
            name: backend    
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec: 
  selector:
      app: backend
      tier: api
      project: expense
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port           


      


